### ISSUE TITLE
Time to remove Android 4?

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/browserslist-config#16]
Looking at our internal browser policy page, I see no mention of the native android web browser, yet we have it in our config:

https://github.com/eBay/browserslist-config/blob/master/index.js#L10

This browser has low traffic and poor ES6 support (it has now become the main "bottleneck" in our Babel transpilation).

https://browserslist.dev/?q=Q2hyb21lID49IDc4LEZpcmVmb3ggPj0gNzgsU2FmYXJpID49IDEwLEVkZ2UgMTgsRWRnZSA%2BPSA4NyxPcGVyYSA%2BPSA3MyxDaHJvbWVBbmRyb2lkID49IDc1LGlvc19zYWYgPj0gOSxBbmRyb2lkID49IDQ%3D

**Comment by abiyasa** [comment]
Thanks @ianmcburnie, Ian for bringing up this issue, I totally miss that one. I completely agree to remove Android 4 native browser from our browserlist.

- Since Android 5, the Android webview went evergreen, and has chrome as default browser (see https://github.com/browserslist/browserslist/issues/374)
- The Android 4.4 has the same engine as chrome mobile version 30, which is far below our minimum version  (see https://developer.chrome.com/docs/multidevice/webview/overview/)

I will create a PR and we can merge it once we get the confirmation.

**Comment by ianmcburnie** [comment]
We have the official go ahead to remove this. We consider it's inclusion here a "bug" and therefore a patch release is probably relevant.

**Comment by abiyasa** [comment]
@ianmcburnie  Merged & published it as v2.0.2
